DjangoBlog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('blog.urls')),
    url(r'^', include('comments.urls')),
]

blog/urls.py
from django.conf.urls import url

from .views import IndexView, ShowView
from . import views

app_name = 'blog'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^blogs/$', IndexView.as_view(), name='index'),
    url(r'^blogs/(?P<id>[0-9]+)/$', ShowView.as_view(), name='show'),
    url(r'^blogs/(?P<id>[0-9]+)/edit/$', views.edit, name='edit'),
    url(r'^blogs/new/$', views.new, name='new'),
]

comments/urls.py
from django.conf.urls import url
from comments.views import IndexView, ShowView

app_name = 'comments'

urlpatterns = [
    url(r'^(?P<blog_id>[0-9]+)/comments/(?P<page>[0-9]+)/$', IndexView.as_view(), name='index'),
    url(r'^comments/(?P<id>[0-9]+)/$', ShowView.as_view(), name='show'),
]

blog/models.py
from datetime import datetime
from django.db import models


class Author(models.Model):
    name = models.CharField(max_length=30)
    honor = models.PositiveIntegerField(default=0)


class BlogManager(models.Manager):
    def get_blog(self, id):
        try:
            return Blog.objects.get(id=id)
        except:
            raise Exception('Blog not found!')

    def create_post(self, data):
        Blog.objects.create(**data).save()

    def update_post(self, id, data):
        post = self.get_blog(id)
        for atr in data:
            setattr(post, atr, data[atr])
        post.save()

    def delete_post(self, id):
        self.get_blog(id).delete()


class Blog(models.Model):
    title = models.CharField(max_length=100)
    image = models.URLField(
        default="http://www.theblogstarter.com/wp-content/uploads/2016/01/start-your-blog-4-steps.png")
    body = models.TextField()
    created = models.DateField(default=datetime.now())
    authors = models.ManyToManyField(Author)
    hidden = models.BooleanField(default=False)

    objects = BlogManager()

blog/views.py
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, Http404, HttpResponse
from django.shortcuts import render
from rest_framework.response import Response
from rest_framework.views import APIView

from blog.models import Blog
from blog.serializers import BlogSerializer


def home(request):
    return HttpResponseRedirect('/blogs')


def new(request):
    return render(request, 'blog/new.html')


def edit(request, id):
    try:
        blog = Blog.objects.get(pk=id)
    except:
        return Http404
    return render(request, 'blog/edit.html', {'blog': blog})


class IndexView(APIView):
    def get(self, request):
        posts = Blog.objects.all()
        serializer = BlogSerializer(posts, many=True)
        return Response({'blogs': serializer.data}, template_name='blog/index.html')

    def post(self, request):
        data = {atr: request.data[atr] for atr in request.data}
        Blog.objects.create_post(data)
        return HttpResponseRedirect('/blogs')


class ShowView(APIView):
    def get(self, request, **kwargs):
        return Response({'blog': BlogSerializer(Blog.objects.get_blog(kwargs['id'])).data},
                        template_name='blog/show.html')

    def put(self, request, *args):
        data = {atr: request.data[atr] for atr in request.data}
        Blog.objects.update_post(args[0], data)
        return HttpResponseRedirect(reverse('blog:show', args=[args[0]]))

    def delete(self, request, *args):
        Blog.objects.delete_post(args[0])
        return HttpResponseRedirect('/blogs')

templates/blog/edit.html
{% include 'blog/partials/header.html' %}
<div class='ui main text container text segment'>
    <div class="ui huge header">Edit {{ blog.title }}</div>
    <form action="/blogs/{{ blog.id }}/" data-method="PUT" class="ui form">
        <div class="field">
            <label>Title</label>
            <input name="title" value="{{ blog.title }}" type='text'>
        </div>
        <div class="field">
            <label>Image</label>
            <input name='image' value="{{ blog.image }}" type="url">
        </div>
        <div class="field">
            <label>Content</label>
            <textarea name='body' placeholder="content of the new post...">{{ blog.body }}</textarea>
        </div>
        <button class="ui violet basic button" type="submit">Save</button>
    </form>
</div>
 <script>
    $(document).ready(function() {
        $('form').ajaxForm();
    });
 </script>

</body>
</html>

templates/blog/index.html
{% include 'blog/partials/header.html' %}
<div class="ui main text container">
    <div class="ui huge header">RESTful Blog</div>
    <div class="ui top attached segment">
        <div class="ui divided items">
            {% for blog in blogs %}
            <div class='item'>
                <div class="image">
                    <img src="{{ blog.image }}">
                </div>
                <div class="content">
                    <a class='header' , href='/blogs/{{ blog.id }}'>{{ blog.title }}</a>
                    <div class="meta">
                        <span>{{ blog.created }} </span>
                    </div>
                    <div class="description">
                        <p>{{ blog.body }}...</p>
                    </div>
                    <div class="extra">
                        <a class='ui floated basic violet button' , href='/blogs/{{ blog.id }}'>
                            Read More
                            <i class="right chevron icon"></i>
                        </a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
</body>
</html>

templates/blog/new.html
{% include 'blog/partials/header.html' %}
<div class='ui main text container text segment'>
    <div class="ui huge header">New Post</div>
    <form action="/blogs/" method="POST" class="ui form">
        <div class="field">
            <label>Title</label>
            <input name="title" placeholder="name of the post" type='text'>
        </div>
        <div class="field">
            <label>Image</label>
            <input name='image' placeholder="url of image" type="url">
        </div>
        <div class="field">
            <label>Content</label>
            <textarea name='body' placeholder="content of the new post..."></textarea>
        </div>
        <button class="ui violet basic button" type="submit">Save</button>
    </form>
</div>
</body>
</html>

templates/blog/show.html
{% include 'blog/partials/header.html' %}
<div class="ui main text container segment">
    <div class="ui huge header">{{ blog.title }}</div>
    <div class="ui top attached">
        <div class="item">
            <img class="ui centered rounded image" src="{{ blog.image }}">
            <div class="content">
                <span>{{ blog.created }}</span>
            </div>
            <div class="description">
                <p>{{ blog.body }}</p>
            </div>
            <a href="/blogs/{{ blog.id }}/edit" class="ui orange basic button">Edit</a>
            <form id="delete" action="/blogs/{{ blog.id }}/" data-method="DELETE">
                <button class="ui red basic button">Delete</button>
            </form>
        </div>
    </div>
</div>

<div id="comments" class="container">
    <iframe src="{% url 'comments:index' blog_id=blog.id page=0 %}" frameborder="0"></iframe>
</div>
 <script>
    $(document).ready(function() {
        $('#delete').ajaxForm();
    });
 </script>
</body>
</html>